
CREATE SCHEMA IF NOT EXISTS controlstock DEFAULT CHARACTER SET utf8 ;
USE controlstock ;
CREATE TABLE IF NOT EXISTS PRODUCTOS (
  id_productos INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  nombre VARCHAR(45) NULL,
  cantidad INTEGER NULL,
  categoria VARCHAR(30) NULL,
  link_ml VARCHAR(300) NULL,
  precio_ml FLOAT NULL,
  precio_venta FLOAT NULL)

#TABLA CLIENTES

CREATE TABLE IF NOT EXISTS CLIENTES (
  id_clientes INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  nombre VARCHAR(45) NULL,
  apellido VARCHAR(45) NULL,
  dni INTEGER NULL,
  direccion VARCHAR(45) NULL,
  tel INTEGER NULL)

#TABLA VENTAS

CREATE TABLE IF NOT EXISTS VENTAS (
id_venta INTEGER PRIMARY KEY AUTOINCREMENT,
id_cliente INTEGER NOT NULL,
id_producto INTEGER NOT NULL,
fecha_venta DATE NULL,
precio_venta FLOAT NULL,
cuotas_totales INTEGER NULL,
cuotas_pagadas INTEGER NULL,
FOREIGN KEY VENTAS(id_cliente) REFENCES CLIENTES(id_clientes),
FOREIGN KEY VENTAS(id_producto) REFENCES PRODUCTOS(id_productos))